FROM ubuntu

USER root
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir -p /var/run/sshd

ADD sshd_config /etc/ssh/sshd_config
WORKDIR /tmp

ENTRYPOINT /usr/sbin/sshd -D
ENTRYPOINT /bin/bash


